#!/bin/bash

HOME_PATH=/home/user/analysis
FASTQ_PATH=$HOME_PATH/fastq
FASTQ_PATTERN=*.fastq.gz
FASTQC_COMMAND=$FASTQC_PATH/fastqc
MULTIQC_COMMAND=$MULTIQC_PATH/multiqc
FASTQC_OUTPUT=$HOME_PATH/fastqc
CORES=8

if [ ! -d $FASTQC_OUTPUT ]
then
    mkdir -p $FASTQC_OUTPUT
fi

$FASTQC_COMMAND --outdir $FASTQC_OUTPUT --threads $CORES $FASTQ_PATH/$FASTQ_PATTERN

$MULTIQC_COMMAND $FASTQC_OUTPUT -o $FASTQC_OUTPUT
